---

#######################################
### ORGANIZATION VARS
#######################################

### ROCKY

# foreman_organization_rocky: "{{ foreman_organization }}"

### ROCKY 8

# foreman_organization_rocky8: "{{ foreman_organization_rocky }}"

# foreman_organization_rocky84: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky85: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky86: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky87: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky88: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky89: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky810: "{{ foreman_organization_rocky8 }}"

# foreman_organization_rocky8_sig_core: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky8_sig_core_common: "{{ foreman_organization_rocky8_sig_core }}"
# foreman_organization_rocky8_sig_core_infra: "{{ foreman_organization_rocky8_sig_core }}"

# foreman_organization_rocky8_sig_cloud: "{{ foreman_organization_rocky8 }}"
# foreman_organization_rocky8_sig_cloud_common: "{{ foreman_organization_rocky8_sig_cloud }}"
# foreman_organization_rocky8_sig_cloud_kernel: "{{ foreman_organization_rocky8_sig_cloud }}"

### ROCKY 9

# foreman_organization_rocky9: "{{ foreman_organization_rocky }}"

# foreman_organization_rocky90: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky91: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky92: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky93: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky94: "{{ foreman_organization_rocky9 }}"

# foreman_organization_rocky9_sig_core: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky9_sig_core_common: "{{ foreman_organization_rocky9_sig_core }}"
# foreman_organization_rocky9_sig_core_infra: "{{ foreman_organization_rocky9_sig_core }}"

# foreman_organization_rocky9_sig_cloud: "{{ foreman_organization_rocky9 }}"
# foreman_organization_rocky9_sig_cloud_common: "{{ foreman_organization_rocky9_sig_cloud }}"
# foreman_organization_rocky9_sig_cloud_kernel: "{{ foreman_organization_rocky9_sig_cloud }}"
